# Generated by Django 4.1.4 on 2022-12-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img1', models.ImageField(default='null', upload_to='carousel')),
                ('car_img2', models.ImageField(default='null', upload_to='carousel')),
                ('car_img3', models.ImageField(default='null', upload_to='carousel')),
                ('car_img4', models.ImageField(default='null', upload_to='carousel')),
                ('car_img5', models.ImageField(default='null', upload_to='carousel')),
                ('car_img6', models.ImageField(default='null', upload_to='carousel')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(max_length=50, unique=True)),
                ('loc_img', models.ImageField(default='null', upload_to='locations')),
                ('zipcode', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('passwordDigest', models.CharField(max_length=300)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('userId', models.IntegerField(unique=True)),
                ('isLoggedIn', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('make', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('mach_img', models.ImageField(default='null', upload_to='machines')),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationID', to='DLS.location')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID', to='DLS.user')),
            ],
        ),
    ]
