# Generated by Django 4.1.4 on 2022-12-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='displayName',
            field=models.CharField(default='default', max_length=500),
        ),
    ]
