# Generated by Django 4.1.4 on 2022-12-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DLS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='car_img5',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='car_img6',
        ),
    ]
