# Generated by Django 4.1.4 on 2022-12-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLS', '0002_comment_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photoURL',
            field=models.CharField(default='default', max_length=500),
        ),
    ]
