# Generated by Django 4.1.4 on 2022-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLS', '0002_remove_carousel_car_img5_remove_carousel_car_img6'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='name',
            field=models.CharField(default='Carousel', max_length=100, unique=True),
        ),
    ]
