# Generated by Django 4.1.4 on 2022-12-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLS', '0003_comment_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
