# Generated by Django 4.1.4 on 2022-12-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DLS', '0003_rename_passworddigest_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwordDigest',
        ),
    ]
