# Generated by Django 4.1.4 on 2022-12-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLS', '0004_alter_location_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='price',
            field=models.DecimalField(decimal_places=2, default='N/A', max_digits=11),
        ),
    ]
