# Generated by Django 4.1.4 on 2023-01-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLS', '0007_alter_machine_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.CharField(default='_blank', max_length=200),
        ),
    ]
